<a href="https://colab.research.google.com/github/Arpitkamal/Deep-learning-107-Introduction-to-Pytorch/blob/master/PytochIntroduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Outline


1.   PyTorch
2.   What are tensors
3.   Initialisation, slicing, reshaping tensors
4.   Numpy and PyTorch interfacing
5.   GPU support for PyTorch + Enabling GPUs on Google Colab
6.   Speed comparisons, Numpy -- PyTorch -- PyTorch on GPU
7.   Autograd concepts and application
8.   Writing a basic learning loop using utograd




In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

# Initialise tensors

In [3]:
x = torch.ones(3, 2)
print(x)
x = torch.zeros(3, 2)
print(x)
x = torch.rand(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.1849, 0.1913],
        [0.9886, 0.3616],
        [0.1740, 0.5979]])


In [4]:
x = torch.empty(3, 2)
print(x)
y = torch.zeros_like(x)
print(y)

tensor([[6.9868e-36, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
x = torch.linspace(0, 1, steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [6]:
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


# Slicing tensors

In [7]:
print(x.size())
print(x[:, 0])
print(x[0, :])

torch.Size([3, 2])
tensor([1, 3, 5])
tensor([1, 2])


In [8]:
y = x[1, 0]
print(y)
print(y.item())

tensor(3)
3


# Reshaping tensors

In [9]:
print(x)
y = x.view(2, 3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
y = x.view(6, -1)
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


# Simple Tensor Operations


In [11]:
x = torch.ones([3, 2])
y = torch.ones([3, 2])
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [12]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [13]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


# Numpy <> PyTorch

In [14]:
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)

[ 0.31245041  0.17434484 -1.2243845  -0.48361544  0.21862733]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([ 0.3125,  0.1743, -1.2244, -0.4836,  0.2186], dtype=torch.float64)


In [16]:
np.add(a, 1, out=a)
print(a)
print(a_pt)

[ 1.31245041  1.17434484 -0.2243845   0.51638456  1.21862733]
tensor([ 1.3125,  1.1743, -0.2244,  0.5164,  1.2186], dtype=torch.float64)


In [17]:
%%time
for i in range(100):
  a = np.random.randn(100,100)
  b = np.random.randn(100,100)
  c = np.matmul(a, b)

CPU times: user 175 ms, sys: 108 ms, total: 283 ms
Wall time: 163 ms


In [18]:
%%time
for i in range(100):
  a = torch.randn(100,100)
  b = torch.randn(100,100)
  c = torch.matmul(a, b)

CPU times: user 52.5 ms, sys: 46.8 ms, total: 99.4 ms
Wall time: 55.7 ms


In [19]:
%%time
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  c = a + b

CPU times: user 1min 33s, sys: 624 ms, total: 1min 34s
Wall time: 1min 34s


In [20]:
%%time
for i in range(10):
  a = torch.randn(10000,10000)
  b = torch.randn(10000,10000)
  c = a + b

CPU times: user 20.9 s, sys: 6.97 ms, total: 20.9 s
Wall time: 20.9 s
